esphome:
  name: ydrip
  friendly_name: "Water meter"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/YDrip/ydrip-esphome.git
      ref: main
    components: [ ydrip ]

# For local development
#external_components:
#  - source:
#      type: local
#      path: ydrip_components

sensor:
  - platform: ydrip
    id: ydrip_sensor
    usage_alert_count: 1024
    leak_alert_count: 32
    low_freq_leak_thresh: 0.125
    usage:
      name: "Water Usage"
    leak:
      name: "Leak Detection"
    battery_level:
      name: "Battery Level"

i2c:
  sda: 4
  scl: 5
  frequency: 400kHz

# Create a file named wifi.yaml that contains the following
#  ssid: "your_ssid"
#  password: "your_wifi_password"
#  fast_connect: true
wifi:
  !include wifi.yaml

api:

deep_sleep:

logger:
  level: DEBUG
  #hardware_uart: UART0

# Comment out "hardware_uart: UART0" above to enable improv serial
improv_serial: